# Generated by Django 6.0 on 2026-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
