# Generated by Django 6.0 on 2025-12-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="weight_kg",
            field=models.FloatField(
                default=0, help_text="Peso aproximado en Kg para el envío"
            ),
        ),
    ]
