# Generated by Django 6.0 on 2026-01-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="auction_end",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_sold",
        ),
    ]
